language: php

php:
  - 7.3

services:
  - docker
  
before_install:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

script:
  - docker build -t sausf93/Practica-Travis:0.0.1 .

deploy:
  - provider: script
    script:
      # push to dockerhub
      docker push sausf/Practica-Travis;
    on:
      branch: master



